### ISSUE TITLE
Running gr-gsm on Raspberry pi 2 or low end device

### ISSUE THREAD

**Issue by zbt160** [ptrkrysik/gr-gsm#168]
Hi,
So after running the gr-gsm on my laptop, I want to run it and receive packets on a low cost hardware like raspberry pi 2 for example. I have manually built the project and my gnuradio-companion interface shows the signal and peaks but the problem is that the i am not getting data (just zeros here or sometimes a packet once in a hour). In order to delve deeper into the problem, i checked the CPU usage by 'top' and it turns out that the python file (airproble_rtlsdr.py or gsm_livemon.py) consume around 170% percent of my pi 2. 

Is there a way about this problem or should i give up my dream to run this on raspberry pi 2.

**Comment by ptrkrysik** [comment]
W dniu 10.03.2016 o 10:46, zbt160 pisze:
> Hi,
> So after running the gr-gsm on my laptop, I want to run it and receive
> packets on a low cost hardware like raspberry pi 2 for example. I have
> manually built the project and my gnuradio-companion interface shows the
> signal and peaks but the problem is that the i am not getting data (just
> zeros here or sometimes a packet once in a hour). In order to delve
> deeper into the problem, i checked the CPU usage by 'top' and it turns
> out that the python file (airproble_rtlsdr.py or gsm_livemon.py) consume
> around 170% percent of my pi 2.
> 
> Is there a way about this problem or should i give up my dream to run
> this on raspberry pi 2.
> 
Currently probably it isn't possible to receive gsm messages in realtime
on ARM. You can easily check this by capturing i.e. one 10 seconds of
data, process it with grgsm_decode and measure time. If this is longer
than 10 seconds it means that grgsm requires optimization in order to
run on ARM devices.

If you want to do this I can provide you some general help about gr-gsm.

P.S. we can continue this discussion on the mailing list. I'm closing
the issue here.
