### ISSUE TITLE
Decode & Decrypt

### ISSUE THREAD

**Issue by hackterr** [ptrkrysik/gr-gsm#26]
Any plans to work on receiving other than 0 TS, decode & decrypt ? 
I would like to contribute.

**Comment by ptrkrysik** [comment]
There's a lot of plans but the time that I can dedicate to the project is too limited to complete them all as fast as I would like. I'm happy to hear about your proposition of help. 

What you need to know to start? I've already prepared decryption block (I will post working version soon). There is decoding for control channels. What is really needed now is a decoding block for traffic channels and traffic channels demapping block (a blocks that takes bursts belonging to one channel and send to a decoder). Processing of control channels in timeslots other than 0 will be added very soon.

What would be also good would be automation of addition of new blocks a'la gnuradio's gr_modtool because addtion of new block costs currently too much time.
