### ISSUE TITLE
What does these grgsm_livemon options do?

### ISSUE THREAD

**Issue by E3V3A** [ptrkrysik/gr-gsm#288]
What does the following `grgsm_livemon` options do? 

```
-o SHIFTOFF, --shiftoff=SHIFTOFF          Set shiftoff [default=400k]
--osr=OSR                                 Set OSR [default=4]
 ```
Clearly, the `SHIFTOFF` is mislabeled and should be some kind of value...

**Comment by E3V3A** [comment]
@ptrkrysik ??

**Comment by axilirator** [comment]
Just look at the follow graph. They are both follow graph variables.
First is used to adjust the phase increment of 'Rotator' block.
Second one is for 'GSM Receiver' and 'GSM Clock Control' blocks.

**Comment by Alster** [comment]
@axilirator I join the question, namely: what is OSR?

**Comment by ptrkrysik** [comment]
OSR stands for OverSampling Ratio - it is number of samples per GSM symbol.

The shiftoff is frequency offset added in order to shift DC offset to another frequency so it is possible to filter it out. The receiver isn't setting its central frequency to the centre of a GSM channel but at a frequency different by SHIFTOFF from it.
