### ISSUE TITLE
Decrypt SMS on hopping SDCCH8 channel

### ISSUE THREAD

**Issue by ppandit26** [ptrkrysik/gr-gsm#328]
Hello,

I have a cfile captured at 25M. The CX hopper block is configured as per the Immediate Assignment. I can see the CM service request and Ciphering Mode Command messages at the output of Control Channel decoder. But I am unable to see any decrypted text (I have configured the decryption block with encryption key and A5/3 version).
MA: 59, 77, 79 
C0:79 
HSN:0 
MAIO:0 
TSEQ:3

I can see the TMSI of my phone in CM Service Request. Can anybody kindly provide any suggestions or inputs?

Best Regards

![hopping_sdcch8](https://user-images.githubusercontent.com/30795745/30028410-41559c90-9185-11e7-8d2b-3e07b5d912bb.png)

**Comment by ptrkrysik** [comment]
Can you see any decrypted messages in wireshark? 

I'm closing the issue here as it is not a topic for issues tracker in gr-gsm, please use https://github.com/ptrkrysik/gr-gsm#mailing-list to continue this thread. You can reference this issue so you won't have to start again (https://github.com/ptrkrysik/gr-gsm/issues/328).
