### ISSUE TITLE
Erroneous Installation Instructions

### ISSUE THREAD

**Issue by dabadee** [ptrkrysik/gr-gsm#366]
During the following step from installation instruction

sudo pybombs prefix init /usr/local -a default_prx -R gnuradio-default
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.prefix - ERROR - Could not find recipe for `gnuradio-default'

The following step should be included in installation instruction before this step

sudo pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git

**Comment by velichkov** [comment]
Hi @dabadee,

Thanks for reporting this. Yesterday I added the `-R gnuradio-default` to the init command because apache-thrift installation fails on some platforms and as a result the installation of gr-gsm fails. In the [gnuradio-defualt the `apache-thrift` is marked as optional](https://github.com/gnuradio/gr-recipes/blob/master/gnuradio-default.lwr#L25-L26) and the failure is ignored.

Instead of manually adding both `gr-recipes` and `gr-etcetera` we could use `pybombs recipes add-defaults` according to https://github.com/gnuradio/pybombs#quickstart

I just updated the wiki.
